apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYzJGcFgydDFiV0Z5T2xOaGFXdDFRREl3TURFPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
